language: go

go:
- 1.8
- 1.9

env:
  global:
  - DOCKER_COMPOSE_VERSION="1.7.1"

install:
- go get -v github.com/pkg/errors
- go get -v github.com/gorilla/mux
- go get -v github.com/mattn/goveralls
- go get -v github.com/stretchr/testify/...
- go get -v github.com/go-openapi/swag
- go get -v github.com/go-openapi/loads
- go get -v github.com/go-openapi/analysis
- go get -v github.com/go-openapi/spec
- go get -v github.com/go-openapi/validate


before_script:
- go get -u github.com/alecthomas/gometalinter
- gometalinter --install

script:
- go vet -v
- gometalinter --deadline=10m --config=.gometalinter.json
- go test -v -covermode=count -coverprofile=profile.cov .

after_success:
- goveralls -coverprofile=profile.cov -service=travis-ci
